package com.krezzsy.skillcrossing.controller;

public enum CommandName {
	CHANGE_LANGUAGE, SIGN_UP, SIGN_IN, GO_TO_ABOUT, GO_TO_LOGIN, GO_TO_MAIN, GO_TO_DISCUSSIONS, GO_TO_CONTACTS, GO_TO_SPEAKERS, GO_TO_STORE, GO_TO_STORE_SECOND_PAGE, GO_TO_STORE_THIRD_PAGE, GO_TO_STORE_FOURTH_PAGE, GO_TO_FAQ, GO_TO_USER_PROFILE, SUBSCRIBE, CONTACT, LOG_OUT, GO_TO_INBOX, GO_TO_ADMIN_PROFILE, GO_TO_SEND_MAIL, GO_TO_ACCOUNT_SETTINGS, CHANGE_SETTINGS, BLOCK_USER, SHOW_INFO, SEARCH
}
